### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by camerondodd** [camerondodd/capstone2#3]
I am having a terrible time setting it up, so it will run Travis CI without posting key.js to github.  I have tried using the env variables with no luck, I have tried encrypting the keys with no luck, and finally I found out travis can encrypt the entire file.  It is very easy, you just need to run

travis encrypt-file config/keys.js --add

The only problem is that it doesn't work if you run it on Windows.  I don't particularly want to set up a new virtual machine and an entire dev environment and clone the repo just to run one tiny line of code.  Could you please run the code and add the keys.js.enc and the updated travis.yml to the repo?

Alternatively, I am happy to hear other options, but I have already read all the travis docs, and I am just not getting something.

Thank you.

**Comment by krokhale** [comment]
All set, pushed to master. You might want to look at trying this:

    https://c9.io/

They have linux terminal in the browser.
